### ISSUE TITLE
[TODO]残された課題一覧

### ISSUE THREAD

**Issue by ryo-manba** [ryo-manba/miniRT#20]
Mandatory
- [X] 解像度を指定できるようにする(いらなかった)

Bonus
- [x] 色付きライト＆マルチスポットライトの対応
- [x] 物体を1つ追加する: Cone, Hyperboloid, Paraboloid..
- [x] チェック柄(チェスボードみたいな柄)を扱う
- [x] bump map テクスチャを扱う

##他にあれば追記お願いします！##

**Comment by ryo-manba** [comment]
解像度の指定をやろうと思うんですが、他にやるべきことあればお伝え下さい！

**Comment by ryo-manba** [comment]
> • your miniRT must be able to render in any positive resolution size (use 1080p by
default for evaluation).

解像度の件ですが、WIDTH, HEIGHTを変えても正しくレンダリングできるよね？って話みたいです。
デフォルトで、W=1920, H=1080 にしておいてねと。
そのため、特別なにか加える必要はないと判断しました。

**Comment by ryo-manba** [comment]
次、チェック柄のやつやります！
他にやるべき(以下ry
